apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "fin-pfe-claims-hellow"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fin-platform-team/fin-catalog-claims"
    targetRevision: HEAD
    path: "claims/hellow"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
